# Generated by Django 5.2.6 on 2025-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paywall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=255)),
                ('amount', models.IntegerField(default=500)),
            ],
        ),
    ]
