# Generated by Django 5.2.6 on 2025-09-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('washer', 'Washer'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
