# Generated by Django 5.2.6 on 2025-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_loyaltypoints_review_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned to Employee'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Supervisor Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
